// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  DynamicContextProvider,
  // DynamicWidget  <-- Only used in /wallet page, so not here
} from "@dynamic-labs/sdk-react-core";
import { DynamicWagmiConnector } from "@dynamic-labs/wagmi-connector";
import { createConfig, WagmiProvider } from "wagmi";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http } from "viem";
import { mainnet } from "viem/chains";

import { usePathname } from "next/navigation";
import { WalletDrawer } from "@/components/ui/drawer"; 
import { AppNav } from "@/components/ui/navigation-menu";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// WAGMI + viem config
const config = createConfig({
  chains: [mainnet],
  multiInjectedProviderDiscovery: false,
  transports: {
    [mainnet.id]: http(),
  },
});

// React Query
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isWalletPage = pathname === "/wallet"; 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DynamicContextProvider
          settings={{
            // Replace "YOUR_ENVIRONMENT_ID" or pull from env:
            // environmentId: process.env.NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID || "",
            environmentId: "YOUR_ENVIRONMENT_ID",
            walletConnectors: [], 
          }}
        >
          <WagmiProvider config={config}>
            <QueryClientProvider client={queryClient}>
              <DynamicWagmiConnector>
                {/* Top Navigation Bar */}
                <header className="flex w-full justify-center border-b py-2">
                  <AppNav />
                  {/* If not on the wallet page, show the drawer trigger */}
                  {!isWalletPage && (
                    <div className="ml-4">
                      <WalletDrawer />
                    </div>
                  )}
                </header>

                {/* Main Content */}
                <main>{children}</main>
              </DynamicWagmiConnector>
            </QueryClientProvider>
          </WagmiProvider>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
